Citizen.CreateThread(function()
    RegisterCommand("setap", function()
        SetPedArmour(GetPlayerPed(-1),400)
    end)
    RegisterCommand("sethp", function()
        SetEntityHealth(GetPlayerPed(-1),200)
    end)
    RegisterCommand("getloc", function()
        print(GetEntityCoords(GetPlayerPed(-1)))
    end)
    RegisterCommand("kill", function()
        SetEntityHealth(GetPlayerPed(-1),0)
    end)
    RegisterCommand("car", function(source,args)
        local carName = args[1] or 'adder'
        RequestModel(carName)
        local playerPed = GetPlayerPed(-1)
        local pos = GetEntityCoords(playerPed)
        local plyCar = CreateVehicle(carName, pos.x,pos.y,pos.z, GetEntityHeading(playerPed), true,false)
        SetPedIntoVehicle(playerPed, plyCar, -1)
        SetEntityAsNoLongerNeeded(plyCar)
        SetModelAsNoLongerNeeded(carName)
    end)
end)
